# local
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mysqldb
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      flab:
        bbt: trace
    org:
      springframework:
        transaction: TRACE
---
# production
spring:
  datasource:
    url: jdbc:mysql://223.130.132.156:3307/mysqldb?useSSL=false
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
  profiles:
    active: prod
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      flab:
        bbt: trace
    org:
      springframework:
        transaction: TRACE
