# production1
spring:
  datasource:
    url: jdbc:mysql://223.130.132.156:3307/mysqldb?useSSL=false&autoReconnect=true
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
  config:
    activate:
      on-profile: prod1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    com:
      flab:
        bbt: trace
    org:
      springframework:
        transaction: TRACE

management:
  health:
    defaults:
      enabled: false
---
# production2
spring:
  datasource:
    url: jdbc:mysql://223.130.132.156:3307/mysqldb?useSSL=false&autoReconnect=true
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
  config:
    activate:
      on-profile: prod2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    com:
      flab:
        bbt: trace
    org:
      springframework:
        transaction: TRACE

management:
  health:
    defaults:
      enabled: false
---
# local
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mysqldb
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
    auto-commit: false
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config: classpath:log4j2.xml
  level:
    com:
      flab:
        bbt: trace
    org:
      springframework:
        transaction: TRACE