spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mysqldb
    username: flab-bbt
    password: flab-bbt
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      flab:
        bbt: trace